// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.11.1.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'package:freezed_annotation/freezed_annotation.dart' hide protected;
import 'package:meta/meta.dart' as meta;
part 'simple.freezed.dart';

// These functions are ignored because they are not marked as `pub`: `calculate_subfolder_size`, `contains_subpath`, `dir_contains_file`, `is_not_hidden`

Future<FilesInDirResult> getAllFilesInDir({required String path}) =>
    RustLib.instance.api.crateApiSimpleGetAllFilesInDir(path: path);

Future<DirSizeResult> getDirSize({required String path}) => RustLib.instance.api.crateApiSimpleGetDirSize(path: path);

Future<List<FSEntityInfo>> findParentForFiles({
  required String startPath,
  required String filename,
}) =>
    RustLib.instance.api.crateApiSimpleFindParentForFiles(
      startPath: startPath,
      filename: filename,
    );

Future<List<FSEntityInfo>> findDirectoriesWithFileParallel({
  required String startPath,
  required String filename,
}) =>
    RustLib.instance.api.crateApiSimpleFindDirectoriesWithFileParallel(
      startPath: startPath,
      filename: filename,
    );

/// Optimized: returns FSEntityInfo of files named `filename`, skipping deeper traversal once found
Future<List<FSEntityInfo>> findDirectoriesWithFileEfficient({
  required String startPath,
  required String filename,
}) =>
    RustLib.instance.api.crateApiSimpleFindDirectoriesWithFileEfficient(
      startPath: startPath,
      filename: filename,
    );

Future<List<String>> findDirs({
  required String startPath,
  required String dirName,
}) =>
    RustLib.instance.api.crateApiSimpleFindDirs(
      startPath: startPath,
      dirName: dirName,
    );

Future<List<String>> findDirsExcludingSubpaths({
  required String startPath,
  required String dirName,
  required String fileName,
}) =>
    RustLib.instance.api.crateApiSimpleFindDirsExcludingSubpaths(
      startPath: startPath,
      dirName: dirName,
      fileName: fileName,
    );

Future<List<FSEntityInfo>> getSubfolders({required String path}) =>
    RustLib.instance.api.crateApiSimpleGetSubfolders(path: path);

Future<List<FSEntityInfo>> getFiles({required String path}) => RustLib.instance.api.crateApiSimpleGetFiles(path: path);

Future<List<String>> findFilesWithNameIn({
  required String startPath,
  required String filename,
}) =>
    RustLib.instance.api.crateApiSimpleFindFilesWithNameIn(
      startPath: startPath,
      filename: filename,
    );

Future<Map<String, BigInt>> getSubfolderSizesForBasepaths({
  required List<String> basePaths,
  required List<String> subfolders,
}) =>
    RustLib.instance.api.crateApiSimpleGetSubfolderSizesForBasepaths(
      basePaths: basePaths,
      subfolders: subfolders,
    );

@freezed
@meta.immutable
sealed class DirSizeResult with _$DirSizeResult {
  const factory DirSizeResult({
    required String path,
    required int nFiles,
    required BigInt len,
  }) = _DirSizeResult;
}

@freezed
@meta.immutable
sealed class FilesInDirResult with _$FilesInDirResult {
  const factory FilesInDirResult({
    required String path,
    required List<FSEntityInfo> files,
  }) = _FilesInDirResult;
}

@freezed
@meta.immutable
sealed class FSEntityInfo with _$FSEntityInfo {
  const factory FSEntityInfo({required String path, required BigInt len}) = _FSEntityInfo;
}
